#########################################################################
#ID     Suffix          Mime Content-Type               Server File Type#
#########################################################################
shn	shn		audio/shn			audio
