#
# shn transcode using ffmpeg instead of wmadec
# 
shn mp3 * *
	# F:{PATH=%f}R:{PATH=%F}T:{START=-ss %s}B:{BITRATE=--abr %B}
	[ffmpeg] -loglevel quiet $PATH$  -i $FILE$ -f wav - | [lame] --silent -q $QUALITY$ $BITRATE$ - -

shn flc * *
	# F:{PATH=%f}R:{PATH=%F}T:{START=-ss %s}
	[ffmpeg] -v 0 $START$ -i $PATH$ -f flac - 

shn wav * *
	# F:{PATH=%f}R:{PATH=%F}T:{START=-ss %s}
	[ffmpeg] -v 0 $START$ -i $PATH$ -f wav - 

shn pcm * *
	# F:{PATH=%f}R:{PATH=%F}T:{START=-ss %s}
	[ffmpeg] -v 0 -i $FILE$ -f s16le - 
	
